// <auto-generated />
using MercadoEletronico.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MercadoEletronico.API.Migrations
{
    [DbContext(typeof(MercadoEletronicoContext))]
    [Migration("20210510152559_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("MercadoEletronico.API.Models.ItemPedido", b =>
                {
                    b.Property<int>("idItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("idPedido")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("precoUnitario")
                        .HasColumnType("TEXT");

                    b.Property<int>("qtd")
                        .HasColumnType("INTEGER");

                    b.HasKey("idItem");

                    b.HasIndex("idPedido");

                    b.ToTable("ItemPedido");
                });

            modelBuilder.Entity("MercadoEletronico.API.Models.Pedido", b =>
                {
                    b.Property<int>("idPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("pedido")
                        .HasColumnType("TEXT");

                    b.HasKey("idPedido");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("MercadoEletronico.API.Models.ItemPedido", b =>
                {
                    b.HasOne("MercadoEletronico.API.Models.Pedido", "Pedido")
                        .WithMany("itens")
                        .HasForeignKey("idPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("MercadoEletronico.API.Models.Pedido", b =>
                {
                    b.Navigation("itens");
                });
#pragma warning restore 612, 618
        }
    }
}
